(function(){
const store=window.IuteStore;let data=store.loadData();const loginPanel=document.getElementById("loginPanel"),adminPanel=document.getElementById("adminPanel"),loginNotice=document.getElementById("loginNotice");
function isAuthed(){return sessionStorage.getItem("iuteAdminAuthed")==="1"}
function showAdmin(){loginPanel.classList.add("is-hidden");adminPanel.classList.remove("is-hidden");localStorage.setItem(store.OWNER_KEY,"1");renderAll()}
function tryLogin(){data=store.loadData();if(document.getElementById("adminPassword").value===data.password){sessionStorage.setItem("iuteAdminAuthed","1");showAdmin()}else loginNotice.textContent="Неверный пароль."}
function saveAndRender(passwordOverride){store.saveData(data,passwordOverride||data.password);renderAll()}
function field(label,value,onInput,wide){const id=store.cryptoId();setTimeout(()=>{let i=document.getElementById(id);if(i)i.oninput=e=>onInput(e.target.value)});return`<label class="${wide?"wide":""}"><span>${label}</span><input id="${id}" type="text" value="${store.escapeHtml(value||"")}"></label>`}
function area(label,value,onInput){const id=store.cryptoId();setTimeout(()=>{let i=document.getElementById(id);if(i)i.oninput=e=>onInput(e.target.value)});return`<label class="wide"><span>${label}</span><textarea id="${id}" rows="4">${store.escapeHtml(value||"")}</textarea></label>`}
function fileField(card){return`<label class="wide"><span>Загрузить фото с компьютера</span><div class="file-upload"><input data-card-file="${card.id}" type="file" accept="image/*"></div></label>`}
function renderCards(){let list=document.getElementById("cardsAdminList");list.innerHTML=data.cards.map(c=>`<article class="admin-item"><img class="admin-thumb" src="${store.escapeHtml(c.image)}" alt="" onerror="this.onerror=null;this.src='banner.jpg';"><div class="admin-fields">${field("Название",c.title,v=>c.title=v)}${field("Фото / ссылка / data URL",c.image,v=>c.image=v)}${fileField(c)}${area("Описание",c.description,v=>c.description=v)}${field("Текст кнопки",c.button,v=>c.button=v)}${field("Ссылка перехода",c.url,v=>c.url=v)}<div class="row-actions wide"><button class="btn primary" data-save type="button">Сохранить</button><button class="btn danger" data-delete-card="${c.id}" type="button">Удалить</button></div></div></article>`).join("")}
function renderAvailability(){if(!data.availability)data.availability={eyebrow:"наличие",title:"Наличие",cities:[]};if(!Array.isArray(data.availability.cities))data.availability.cities=[];document.getElementById("availabilityEyebrowInput").value=data.availability.eyebrow||"";document.getElementById("availabilityTitleInput").value=data.availability.title||"";document.getElementById("availabilityAdminList").innerHTML=data.availability.cities.map(c=>`<article class="admin-item no-image"><div class="admin-fields">${field("Город",c.name,v=>c.name=v)}${field("Ссылка кнопки Telegram",c.url||"https://t.me/iute555bot",v=>c.url=v)}${area("Описание для города",c.description,v=>c.description=v)}<div class="row-actions wide"><button class="btn primary" data-save type="button">Сохранить</button><button class="btn danger" data-delete-city="${c.id}" type="button">Удалить</button></div></div></article>`).join("")}
function renderChats(){document.getElementById("chatsAdminList").innerHTML=data.chats.map(c=>`<article class="admin-item no-image"><div class="admin-fields">${field("Название кнопки",c.title,v=>c.title=v)}${field("Подпись",c.hint,v=>c.hint=v)}${field("Ссылка",c.url,v=>c.url=v,true)}<div class="row-actions wide"><button class="btn primary" data-save type="button">Сохранить</button><button class="btn danger" data-delete-chat="${c.id}" type="button">Удалить</button></div></div></article>`).join("")}
function renderReviews(){let list=document.getElementById("reviewsAdminList");if(!data.reviews.length){list.innerHTML='<div class="panel"><p class="muted">Отзывов пока нет.</p></div>';return}list.innerHTML=data.reviews.map(r=>`<article class="admin-item no-image"><div class="admin-fields"><div><span class="status-pill">${r.approved?"Одобрен":"Ждет одобрения"}</span><h3>${store.escapeHtml(r.login)}</h3><div class="review-rating">${"★".repeat(Number(r.rating||5))}${"☆".repeat(5-Number(r.rating||5))}</div><p class="muted">${store.formatDate(r.createdAt)}</p></div><p>${store.escapeHtml(r.text)}</p><div class="row-actions wide"><button class="btn primary" data-toggle-review="${r.id}" type="button">${r.approved?"Скрыть":"Одобрить"}</button><button class="btn danger" data-delete-review="${r.id}" type="button">Удалить</button></div></div></article>`).join("")}
function renderNews(){document.getElementById("newsEnabled").checked=Boolean(data.news.enabled);document.getElementById("newsTitleInput").value=data.news.title||"";document.getElementById("newsTextInput").value=data.news.text||""}
function renderHero(){if(!data.hero)data.hero={};document.getElementById("heroEyebrowInput").value=data.hero.eyebrow||"";document.getElementById("heroTitleInput").value=data.hero.title||"";document.getElementById("heroDescriptionInput").value=data.hero.description||"";document.getElementById("heroLogoInput").value=data.hero.logo||"logo.jpg";document.getElementById("heroBannerInput").value=data.hero.banner||"banner.jpg"}
function renderAll(){renderHero();renderCards();renderAvailability();renderChats();renderReviews();renderNews()}
function resizeImage(file){return new Promise((resolve,reject)=>{let reader=new FileReader();reader.onerror=reject;reader.onload=()=>{let img=new Image();img.onerror=reject;img.onload=()=>{let max=1600,ratio=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*ratio)),h=Math.max(1,Math.round(img.height*ratio)),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;let ctx=canvas.getContext("2d");ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL("image/jpeg",.88))};img.src=String(reader.result||"")};reader.readAsDataURL(file)})}
document.getElementById("loginBtn").onclick=tryLogin;document.getElementById("adminPassword").onkeydown=e=>{if(e.key==="Enter")tryLogin()};
document.querySelectorAll(".tab-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab-btn").forEach(x=>x.classList.remove("is-active"));document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");document.getElementById("tab-"+b.dataset.tab).classList.add("is-active")});
document.getElementById("addCard").onclick=()=>{data.cards.unshift({id:store.cryptoId(),title:"Новая карточка",description:"Описание можно изменить в админ панели.",image:"banner.jpg",button:"Перейти",url:"https://tut.contact/iutecc"});saveAndRender()};
document.getElementById("addChat").onclick=()=>{data.chats.unshift({id:store.cryptoId(),title:"Новая кнопка",hint:"@username",url:"https://t.me/username"});saveAndRender()};
document.getElementById("addCity").onclick=()=>{if(!data.availability)data.availability={eyebrow:"наличие",title:"Наличие",cities:[]};data.availability.cities.unshift({id:store.cryptoId(),name:"Новый город",description:"Описание можно изменить в админ панели.",url:"https://t.me/iute555bot"});saveAndRender()};
document.getElementById("saveAvailabilityTitle").onclick=()=>{if(!data.availability)data.availability={cities:[]};data.availability.eyebrow=document.getElementById("availabilityEyebrowInput").value;data.availability.title=document.getElementById("availabilityTitleInput").value;saveAndRender()};
document.getElementById("saveNews").onclick=()=>{data.news.enabled=document.getElementById("newsEnabled").checked;data.news.title=document.getElementById("newsTitleInput").value;data.news.text=document.getElementById("newsTextInput").value;saveAndRender()};
document.getElementById("saveHero").onclick=()=>{data.hero={eyebrow:document.getElementById("heroEyebrowInput").value,title:document.getElementById("heroTitleInput").value,description:document.getElementById("heroDescriptionInput").value,logo:document.getElementById("heroLogoInput").value||"logo.jpg",banner:document.getElementById("heroBannerInput").value||"banner.jpg"};saveAndRender()};
document.getElementById("savePassword").onclick=()=>{let v=document.getElementById("newPassword").value.trim();if(v.length<4)return;let old=data.password;data.password=v;document.getElementById("newPassword").value="";saveAndRender(old)};
document.getElementById("logoutBtn").onclick=()=>{sessionStorage.removeItem("iuteAdminAuthed");localStorage.removeItem(store.OWNER_KEY);location.href="index.html"};
document.onclick=e=>{let t=e.target;if(!(t instanceof HTMLElement))return;if(t.matches("[data-save]"))saveAndRender();if(t.dataset.deleteCard){data.cards=data.cards.filter(c=>c.id!==t.dataset.deleteCard);saveAndRender()}if(t.dataset.deleteChat){data.chats=data.chats.filter(c=>c.id!==t.dataset.deleteChat);saveAndRender()}if(t.dataset.deleteCity&&data.availability){data.availability.cities=data.availability.cities.filter(c=>c.id!==t.dataset.deleteCity);saveAndRender()}if(t.dataset.toggleReview){let r=data.reviews.find(x=>x.id===t.dataset.toggleReview);if(r)r.approved=!r.approved;saveAndRender()}if(t.dataset.deleteReview){data.reviews=data.reviews.filter(r=>r.id!==t.dataset.deleteReview);saveAndRender()}};
document.onchange=e=>{let input=e.target;if(!(input instanceof HTMLInputElement))return;let file=input.files&&input.files[0];if(!file||!file.type.startsWith("image/"))return;if(input.id==="heroLogoFile"||input.id==="heroBannerFile"){resizeImage(file).then(result=>{if(!data.hero)data.hero={};if(input.id==="heroLogoFile"){data.hero.logo=result||"logo.jpg";document.getElementById("heroLogoInput").value=data.hero.logo}else{data.hero.banner=result||"banner.jpg";document.getElementById("heroBannerInput").value=data.hero.banner}saveAndRender()});return}if(!input.dataset.cardFile)return;let card=data.cards.find(x=>x.id===input.dataset.cardFile);if(!card)return;resizeImage(file).then(result=>{card.image=result||"banner.jpg";saveAndRender()}).catch(()=>{card.image="banner.jpg";saveAndRender()})};
store.loadServerData?.().then(changed=>{if(changed)data=store.loadData();if(isAuthed())showAdmin()});
})();
