(function(){
const STORAGE_KEY="iuteSiteData",OWNER_KEY="iuteOwnerMode",DEFAULT_PASSWORD="iutecc228",BOT="https://t.me/iute555bot";
function cryptoId(){return crypto&&crypto.randomUUID?crypto.randomUUID():"id-"+Math.random().toString(16).slice(2)+Date.now()}
const defaults={password:DEFAULT_PASSWORD,news:{enabled:true,title:"Актуальные новости",text:"Здесь владелец может написать свежую информацию для посетителей. Текст, заголовок и показ окна меняются в админ панели."},hero:{eyebrow:"локальная визитка",title:"Iute 🌶",description:"Сайт создан для того что бы вы были в курсе каждый день актуальных новостей/наличий и контактов"},availability:{eyebrow:"наличие",title:"Наличие",cities:["Кишинев","Бельцы","Фалешты","Унгены"].map(n=>({id:cryptoId(),name:n,description:"Актуальное наличие и новости по городу можно менять в админ панели.",url:BOT}))},cards:[{id:cryptoId(),title:"Iute 🌶",description:"Постоянный переход на актуальную страницу с контактами и обновлениями.",image:"banner.jpg",button:"Перейти",url:"https://tut.contact/iutecc"},{id:cryptoId(),title:"Каталог",description:"Быстрый доступ к разделу с удобной навигацией и свежими обновлениями.",image:"logo.jpg",button:"Открыть",url:"https://tut.contact/iutecc"},{id:cryptoId(),title:"Поддержка",description:"Контакт для вопросов, уточнений и связи с оператором.",image:"banner.jpg",button:"Написать",url:"https://t.me/iuteccc"}],chats:[{id:cryptoId(),title:"Оператор",hint:"@iuteccc",url:"https://t.me/iuteccc"},{id:cryptoId(),title:"Маркетолог",hint:"@marketologccc",url:"https://t.me/marketologccc"},{id:cryptoId(),title:"Отзывы",hint:"Telegram",url:"https://t.me/+uV5gGpLumI43ZjE6"},{id:cryptoId(),title:"Стикеры",hint:"Набор",url:"https://t.me/addstickers/iutecc"}],reviews:[{id:cryptoId(),login:"@moskva",text:"в касаний",createdAt:new Date(Date.now()-5400000).toISOString(),approved:true,rating:4},{id:cryptoId(),login:"@sasha227",text:"лучшие",createdAt:new Date(Date.now()-93600000).toISOString(),approved:true,rating:5},{id:cryptoId(),login:"@bratmsk",text:"Был ннх спустя 17 раз покупки опер быстро среагировал выдал пз",createdAt:new Date(Date.now()-183900000).toISOString(),approved:true,rating:4},{id:cryptoId(),login:"@bigpack7",text:"хороший товар,лучший на рынке брат",createdAt:new Date(Date.now()-291300000).toISOString(),approved:true,rating:5}],seedVersion:4};
const clone=v=>JSON.parse(JSON.stringify(v));
function normAvail(v){const s=v&&typeof v==="object"?v:{},cs=Array.isArray(s.cities)&&s.cities.length?s.cities:defaults.availability.cities;return{eyebrow:s.eyebrow||defaults.availability.eyebrow,title:s.title||defaults.availability.title,cities:cs.map(c=>({id:c.id||cryptoId(),name:c.name||"Город",description:c.description||"",url:c.url||BOT}))}}
function normCard(c,i){c={...c};if(!c.image||String(c.image).includes("assets/iute"))c.image=i%2?"logo.jpg":"banner.jpg";return c}
function enrich(saved){let rs=Array.isArray(saved.reviews)?saved.reviews:[],old=new Set(["@alex_m","@vika_online","@roman_77","@visitor","@testuser","@v_kasanii","@top_client","@nnxbuyer","@brat_market"]);rs=rs.filter(r=>Number(saved.seedVersion||0)>=defaults.seedVersion||!old.has(r.login)).map(r=>({...r,rating:Number(r.rating||5)}));if(Number(saved.seedVersion||0)>=defaults.seedVersion)return rs;let have=new Set(rs.map(r=>r.login));return[...defaults.reviews.filter(r=>!have.has(r.login)),...rs]}
function mergeData(saved){if(!saved||typeof saved!=="object")return clone(defaults);return{password:!saved.password||saved.password==="iute2026"?DEFAULT_PASSWORD:saved.password,news:{...defaults.news,...(saved.news||{})},hero:{...defaults.hero,...(saved.hero||{})},availability:normAvail(saved.availability),cards:Array.isArray(saved.cards)?saved.cards.map(normCard):clone(defaults.cards),chats:Array.isArray(saved.chats)?saved.chats:clone(defaults.chats),reviews:enrich(saved),seedVersion:Math.max(Number(saved.seedVersion||0),defaults.seedVersion)}}
function loadData(){try{return mergeData(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch(e){return clone(defaults)}}
function saveData(data,password){data.seedVersion=Math.max(Number(data.seedVersion||0),defaults.seedVersion);localStorage.setItem(STORAGE_KEY,JSON.stringify(data));if(password)fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json","X-Admin-Password":password},body:JSON.stringify(data)}).catch(()=>{})}
async function loadServerData(){try{let r=await fetch("/api/data",{cache:"no-store"});if(!r.ok)return false;let v=await r.json();if(!v||!Object.keys(v).length)return false;localStorage.setItem(STORAGE_KEY,JSON.stringify(mergeData(v)));return true}catch(e){return false}}
function submitReview(review,data){data.reviews.unshift(review);saveData(data);fetch("/api/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(review)}).catch(()=>{})}
function escapeHtml(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function formatDate(v){return new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
function normalizeUrl(u){u=String(u||"").trim();if(!u)return"#";if(u.startsWith("@"))return"https://t.me/"+u.slice(1);if(/^[a-z]+:\/\//i.test(u))return u;if(u.startsWith("t.me/")||u.startsWith("tut.contact/"))return"https://"+u;return u}
function stars(r){r=Math.max(1,Math.min(5,Number(r||5)));return"★".repeat(r)+"☆".repeat(5-r)}
function renderHero(d){let e=document.getElementById("heroEyebrow"),t=document.getElementById("heroTitle"),p=document.getElementById("heroDescription");if(e)e.textContent=d.hero.eyebrow;if(t)t.textContent=d.hero.title;if(p)p.textContent=d.hero.description}
function renderCards(d){let g=document.getElementById("cardGrid");if(!g)return;g.innerHTML=d.cards.map(c=>`<article class="link-card"><img src="${escapeHtml(c.image)}" alt="${escapeHtml(c.title)}" onerror="this.onerror=null;this.src='banner.jpg';"><div class="link-card-body"><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.description)}</p><a class="btn primary" href="${escapeHtml(normalizeUrl(c.url))}" target="_blank" rel="noopener">${escapeHtml(c.button||"Перейти")}</a></div></article>`).join("")}
function renderAvailability(d){let s=document.getElementById("availability"),tabs=document.getElementById("cityTabs"),desc=document.getElementById("cityDescription");if(!s||!tabs||!desc)return;let cs=d.availability?.cities||[];if(!cs.length){s.classList.add("is-hidden");return}s.classList.remove("is-hidden");document.getElementById("availabilityEyebrow").textContent=d.availability.eyebrow;document.getElementById("availabilityTitle").textContent=d.availability.title;let selected=cs[0].id;function paint(){let c=cs.find(x=>x.id===selected)||cs[0];tabs.querySelectorAll(".city-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.cityId===c.id));desc.innerHTML=`<h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.description).replaceAll("\n","<br>")}</p><a class="btn primary city-link" href="${escapeHtml(normalizeUrl(c.url||BOT))}" target="_blank" rel="noopener">Перейти в Telegram</a>`}tabs.innerHTML=cs.map((c,i)=>`<button class="city-tab ${i?"":"is-active"}" type="button" data-city-id="${escapeHtml(c.id)}">${escapeHtml(c.name)}</button>`).join("");tabs.onclick=e=>{let b=e.target.closest(".city-tab");if(b){selected=b.dataset.cityId;paint()}};paint()}
function renderChats(d){let l=document.getElementById("chatList");if(!l)return;l.innerHTML=d.chats.map(c=>`<a class="chat-button" href="${escapeHtml(normalizeUrl(c.url))}" target="_blank" rel="noopener"><span>${escapeHtml(c.title)}</span><small>${escapeHtml(c.hint||"перейти")}</small></a>`).join("")}
function renderReviews(d){let tr=document.getElementById("reviewTrack");if(!tr)return;let a=d.reviews.filter(r=>r.approved);if(!a.length){tr.innerHTML='<article class="review-card"><strong>Пока нет отзывов</strong><p>Будьте первым, кто оставит отзыв.</p></article>';return}tr.innerHTML=[...a,...a].map(r=>`<article class="review-card"><strong>${escapeHtml(r.login)}</strong><div class="review-rating">${stars(r.rating)}</div><p>${escapeHtml(r.text)}</p><time>${formatDate(r.createdAt)}</time></article>`).join("")}
function setupStars(){let p=document.getElementById("starPicker");if(!p)return;let cur=Number(p.dataset.value||5);function paint(){p.querySelectorAll(".star").forEach(b=>b.classList.toggle("is-active",Number(b.dataset.rating)<=cur))}p.onclick=e=>{let b=e.target.closest(".star");if(b){cur=Number(b.dataset.rating);p.dataset.value=cur;paint()}};p.dataset.value=cur;paint()}
function setupReviewForm(data){let f=document.getElementById("reviewForm");if(!f||f.dataset.bound)return;f.dataset.bound="1";f.onsubmit=e=>{e.preventDefault();let login=document.getElementById("reviewLogin").value.trim(),text=document.getElementById("reviewText").value.trim(),n=document.getElementById("reviewNotice");if(!/^@[A-Za-z0-9_]{4,32}$/.test(login)){n.classList.remove("is-hidden");n.textContent="Логин должен начинаться с @.";return}if(text.length<5){n.classList.remove("is-hidden");n.textContent="Отзыв слишком короткий.";return}submitReview({id:cryptoId(),login,text,createdAt:new Date().toISOString(),approved:false,rating:Number(document.getElementById("starPicker")?.dataset.value||5)},loadData());f.reset();setupStars();n.classList.remove("is-hidden");n.textContent="Отзыв оставлен."}}
function setupNews(d){let o=document.getElementById("newsOverlay");if(!o||!d.news.enabled)return;document.getElementById("newsTitle").textContent=d.news.title;document.getElementById("newsText").textContent=d.news.text;o.classList.remove("is-hidden");let close=()=>o.classList.add("is-hidden");document.getElementById("closeNews").onclick=close;document.getElementById("acceptNews").onclick=close}
function setupOwnerLink(){if(new URLSearchParams(location.search).get("owner")==="1")localStorage.setItem(OWNER_KEY,"1");let l=document.getElementById("adminLink");if(l&&localStorage.getItem(OWNER_KEY)==="1")l.classList.remove("is-hidden")}
function renderPublicPage(){let d=loadData();renderHero(d);renderCards(d);renderAvailability(d);renderChats(d);renderReviews(d);setupStars();setupReviewForm(d);setupNews(d);setupOwnerLink()}
window.IuteStore={STORAGE_KEY,OWNER_KEY,DEFAULT_PASSWORD,cryptoId,loadData,saveData,loadServerData,submitReview,escapeHtml,formatDate,normalizeUrl};
if(document.getElementById("cardGrid")){renderPublicPage();loadServerData().then(changed=>{if(changed)renderPublicPage()})}
})();
